// vue-client/src/views/Register.vue
<template>
    <div class="container mt-3">
        <h2 class="text-info">
            Register or <RouterLink to="/login">Login</RouterLink>
        </h2>
        <form @submit.prevent="register" class="mt-5 mb-5">
            <div class="form-group">
                <label for="email">Email address</label>
                <input
                    class="form-control"
                    name="email"
                    type="email"
                    id="email"
                    v-model="email"
                    placeholder="
            Your Email"
                />
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input
                    class="form-control"
                    name="password"
                    id="password"
                    type="password"
                    v-model="password"
                    placeholder="Your password"
                />
            </div>
            <button type="submit">Envoyer</button>
        </form>
    </div>
</template>

<script>
import config from '@/mixins/config.js';

export default {
    mixins: [config],
    name: 'Register',
    data() {
        return {
            email: '',
            password: '',
        };
    },
    methods: {
        register() {
            this.axios
                .post(`${this.dev_server_url}/users/register`, {
                    email: this.email,
                    password: this.password,
                })
                .then(res => {
                    const { token, user } = res.data;
                    localStorage.setItem('token', token);
                    localStorage.setItem('user', JSON.stringify(user));
                    // setAuthToken(token);
                    // dispatch({ type: REGISTER, payload: token });
                })
                .catch(e => console.error(e));
        },
    },
};
</script>

<style scoped></style>

// client/src/components/auth/Register.jsx
import React, { useState, useContext, useEffect } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import { AuthContext } from '../../contexts/auth';
import { REGISTER, ERROR } from '../../contexts/auth/types';
import AuthForm from './AuthForm';
import setAuthToken from '../../utils/setAuthToken';

const Register = () => {
    const [, dispatch] = useContext(AuthContext);

    const register = data => {
        // Quand on reçoit le token, le mettre dans localStorage
        // Voir on maintient comment une 'session

        // api/users/register

        // fetch : let data = new  FormData();
        //  data.append('data', data);
        axios
            .post('/api/users/register', data)
            .then(res => {
                const { token, user } = res.data;
                localStorage.setItem('token', token);
                localStorage.setItem('user', JSON.stringify(user));
                setAuthToken(token);
                dispatch({ type: REGISTER, payload: token });
            })
            .catch(e => console.error(e));
    };

    return (
        <div className="container">
            <h2 className="text-info mt-3">
                Register or <Link to="/login">Login</Link>
            </h2>
            <AuthForm method={register} />
        </div>
    );
};

export default Register;
