// client/src/components/common/Header.jsx
import { NavLink } from "react-router-dom";
import NavLinks from "./NavLinks";

const Header = () => {
  return (
    <header className="with-background">
      <div className="top-nav container">
        <div className="logo">
          <NavLink exact="true" to="/">
            React / Express / REDIS Ecommerce
          </NavLink>
        </div>
        <NavLinks />
      </div>
    </header>
  );
};

export default Header;

// vue-client/src/components/Header.vue
<template>
    <header class="with-background">
        <div class="top-nav container">
            <div class="logo">
                <RouterLink to="/">
                    React / Express / REDIS Ecommerce
                </RouterLink>
            </div>
            <NavLinks />
        </div>
    </header>
</template>

<script setup>
import NavLinks from '@/components/NavLinks.vue';
</script>
