// vue-admin/src/components/dashboard/CreateProduct.vue
<template>
    <section class="row">
        <div class="mb-5 col-md-8">
            <h1 class="text-primary">
                <i class="fas fa-user" /> Créez un produit
            </h1>

            <form
                encType="multipart/form-data"
                class="form"
                @submit.prevent="createProduct"
            >
                <div class="col-md-6 mb-2">
                    <label for="metaDescription" class="form-label">
                        Catégories du produit
                    </label>
                    <select
                        class="form-select"
                        aria-label="Default select"
                        name="category"
                        v-model="product.category_id"
                    >
                        <option value="">Open this select menu</option>
                        <option
                            v-for="(cat, index) in categories"
                            name="cat"
                            :key="index"
                            :value="cat.id"
                        >
                            {{ cat.name }}
                        </option>
                    </select>
                </div>
                <div class="col-md-6 mb-2">
                    <div class="row">
                        <div>
                            <label for="image" class="form-label">
                                Image principal du produit (1MB max)
                            </label>
                            <input
                                type="file"
                                name="image"
                                class="form-control"
                                id="image"
                                @change="loadImage"
                            />
                            <img
                                :src="product.image"
                                alt="Représentation du produit"
                            />
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="input-group input-group-sm mb-2">
                        <input
                            type="text"
                            placeholder="Product Name"
                            name="title"
                            v-model="product.title"
                            class="form-control"
                        />
                    </div>
                    <div class="input-group input-group-sm mb-2">
                        <input
                            type="text"
                            placeholder="metaDescription"
                            name="metaDescription"
                            v-model="product.metaDescription"
                            class="form-control"
                        />
                    </div>
                    <div class="input-group input-group-sm mb-2">
                        <input
                            type="number"
                            placeholder="priceHT"
                            name="priceHT"
                            v-model="product.priceHT"
                            class="form-control"
                        />
                    </div>
                </div>

                <div class="col-md-6">
                    <label for="body" class="form-label"> Contenu </label>
                    <Wysiwyg
                        placeholder="description"
                        name="description"
                        ref="desc"
                        @changing="setDescription"
                    ></Wysiwyg>
                </div>
                <input
                    type="submit"
                    class="btn btn-primary"
                    value="Create Product"
                />
            </form>
        </div>
        <div class="col-md-3">
            <h2 class="text-center">Products</h2>
            <hr />
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Catégorie</th>
                        <th>Mettre à jour</th>
                        <th>Supprimer</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="product in products">
                        <td v-text="product.title"></td>
                        <td>
                            <button
                                type="button"
                                class="btn btn-danger btn-sm mx-3"
                            >
                                Supprimer
                            </button>
                        </td>
                        <td>
                            <button
                                type="button"
                                class="btn btn-primary btn-sm mx-3"
                            >
                                Update
                            </button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </section>
</template>

<script>
import Wysiwyg from '@/components/dashboard/Wysiwyg.vue';
import requests from '@/mixins/requests.js';
import { axios } from '@/mixins/axios';

export default {
    mixins: [requests],
    components: { Wysiwyg },
    data() {
        return {
            initProd: {
                title: '',
                description: '',
                metaDescription: '',
                priceHT: '',
                category: '',
            },
            product: {
                title: '',
                description: '',
                metaDescription: '',
                priceHT: '',
                category: '',
            },
            products: [],
            categories: [],
        };
    },
    methods: {
        async getProducts() {
            try {
                const response = await fetch(`${this.server_url}/products`);

                this.products = await response.json();
            } catch (e) {
                console.error(e.message);
            }
        },
        setDescription({ target }) {
            this.product['description'] = target.value;
        },
        async createProduct() {
            try {
                const response = await axios.post(
                    `${this.server_url}/products/create`,
                    this.product
                );

                this.products = await response.data.products;
                this.product = this.initProd;
            } catch (e) {
                console.error(e);
            }
        },
        loadImage(e) {
            const file = e.target.files[0];

            const reader = new FileReader();

            reader.readAsDataURL(file);

            reader.onload = e => {
                this.product.image = e.target.result;
            };
        },
    },
    mounted() {
        this.getCategories().then(() => null);
        this.getProducts().then(() => null);
    },
};
</script>

<style scoped>
img {
    max-width: 100%;
}
</style>

// client/src/components/pages/dashboard/CreateProduct.jsx
import React, { useContext, useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import toastr from 'toastr';
import ReactQuill from 'react-quill';
import quillModule from '../../../utils/quillModule';
import { ProductContext } from '../../../contexts/products';
import { CategoryContext } from '../../../contexts/categories';
import { GET_PRODUCTS } from '../../../contexts/products/types';
import { GET_CATEGORIES } from '../../../contexts/categories/types';
// Les champs name pour créer un prod category_id, title, metaDescription, description, priceHT
// + image

// Mettre un bouton d'annulation de editMode

const CreateProduct = () => {
    // /api/products
    // /api/categories
    const initialState = {
        category_id: '',
        title: '',
        metaDescription: '',
        description: '',
        priceHT: '',
        image: '',
    };
    const [formData, setFormData] = useState(initialState);
    const [product, setProduct] = useState(initialState);
    const [editMode, setEditMode] = useState(false);
    const [productState, dispatchProds] = useContext(ProductContext);
    const [categoriesState, dispatchCats] = useContext(CategoryContext);
    const selectRef = useRef();

    useEffect(() => {
        init();
    }, [dispatchProds, dispatchCats]);

    useEffect(() => {
        setFormData(() => {
            return {
                ...product,
                description: product.description,
            };
        });
    }, [product]);

    const init = () => {
        axios
            .get('/api/products')
            .then(res => {
                dispatchProds({ type: GET_PRODUCTS, payload: res.data });
            })
            .catch(e => console.error(e));

        axios
            .get('/api/categories')
            .then(res => {
                dispatchCats({ type: GET_CATEGORIES, payload: res.data });
            })
            .catch(e => console.error(e));
    };

    const onChangeHandler = e => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleChangeQuill = e => {
        return setFormData({ ...formData, description: e.target.innerHTML });
    };

    const loadImage = e => {
        const file = e.target.files[0];
        setFormData({ ...formData, image: file });
        // const reader = new FileReader();
        //
        // reader.readAsDataURL(file);
        //
        // reader.onload = e => {
        //     setFormData({ ...formData, image: file });
        // };
    };

    const onUpdateClick = (prod, e) => {
        e.preventDefault();

        setProduct(() => productState?.products.find(p => p.id === prod.id));

        selectRef.current.value = prod.category_id;

        setEditMode(true);
    };

    const onSubmit = e => {
        e.preventDefault();

        // est'ce une update ? si oui method === 'patch' et url = '/api/products/update'
        let url = '/api/products/create';
        let method = 'post';

        if (editMode) {
            url = '/api/products/update';
            method = 'patch';
        }

        axios.defaults.headers.common['Content-Type'] = 'multipart/form-data';
        axios.defaults.headers.common['Accept'] = 'application/json';
        const data = new FormData(e.target);
        data.append('description', formData.description); // On fait ça pour quill

        axios[method](url, data)
            .then(res => {
                selectRef.current.value =
                    'Cliquer pour sélectionner la catégorie du produit';
                setEditMode(false);
                setProduct(initialState);
                init();
                return setFormData(initialState);
            })
            .catch(e => console.log(e));
    };

    const { title, metaDescription, description, priceHT, image } = formData;

    return (
        <div className="container mt-5 mb-5">
            <div className="row">
                <div className="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h2 className="h2">Page admin products</h2>
                </div>
                <p>
                    il faut : quand on 'submit' le form, on va devoir soit
                    mettre à jour, soit créer un produit, les données de la
                    requête seront les mêmes, l'url changera ainsi que la
                    méthode (POST, PATCH)
                </p>
            </div>

            {/*FormRow */}
            {/*FormRow:first-child*/}

            <div>
                <ul>
                    {productState?.products ? (
                        productState?.products.map(prod => (
                            <li key={prod.id}>
                                <Link
                                    onClick={e => onUpdateClick(prod, e)}
                                    to={prod.title}
                                >
                                    {prod.title}
                                </Link>
                            </li>
                        ))
                    ) : (
                        <p>Vous n'avez pas enregistré de produits</p>
                    )}
                </ul>
            </div>

            <form
                onSubmit={onSubmit}
                encType="multipart/form-data"
                className="form col-md-6"
            >
                <div className="form-group FormGroup">
                    <div className="FormRow">
                        <label className="FormRowLabel" htmlFor="title">
                            Title
                        </label>
                        <input
                            type="text"
                            name="title"
                            id="title"
                            value={title}
                            placeholder="title"
                            onChange={onChangeHandler}
                        />
                    </div>
                </div>
                <div className="form-group FormGroup">
                    <div className="FormRow">
                        <label className="FormRowLabel" htmlFor="prixHT">
                            prixHT
                        </label>
                        <input
                            type="number"
                            name="priceHT"
                            id="prixHT"
                            value={priceHT}
                            placeholder="prixHT en centimes: 1€ = 100cents"
                            onChange={onChangeHandler}
                        />
                    </div>
                </div>
                <div className="form-group FormGroup">
                    <div className="FormRow">
                        <label
                            className="FormRowLabel"
                            htmlFor="metaDescription"
                        >
                            meta desc
                        </label>
                        <input
                            type="text"
                            value={metaDescription}
                            name="metaDescription"
                            id="metaDescription"
                            placeholder="metaDescription"
                            onChange={onChangeHandler}
                        />
                    </div>
                </div>

                <div className=" mb-5">
                    <label className="form-label" htmlFor="description">
                        Description
                    </label>

                    <ReactQuill
                        value={description || ''}
                        name="body"
                        id="body"
                        modules={quillModule}
                        onKeyUp={handleChangeQuill}
                    />
                </div>

                <div className="form-group FormGroup">
                    <div className="FormRow">
                        <label className="FormRowLabel" htmlFor="image">
                            Image
                        </label>
                        <input
                            onChange={loadImage}
                            type="file"
                            name="image"
                            id="image"
                            placeholder="image"
                        />
                    </div>
                    {image ? <img src={image} alt="alt" /> : null}
                </div>
                <div className="form-group FormGroup">
                    <div className="FormRow">
                        <label
                            className="FormRowLabel form-label"
                            htmlFor="category_id"
                        >
                            Category
                        </label>
                        <select
                            className="form-select"
                            name="category_id"
                            id="category_id"
                            onChange={onChangeHandler}
                            ref={selectRef}
                        >
                            <option defaultValue>
                                Cliquer pour sélectionner la catégorie du
                                produit
                            </option>
                            {categoriesState?.categories.map(cat => {
                                return (
                                    <option key={cat.id} value={cat.id}>
                                        {cat.name}
                                    </option>
                                );
                            })}
                        </select>
                    </div>
                </div>

                <button className="btn btn-primary" type="submit">
                    Submit
                </button>
            </form>
        </div>
    );
};

export default CreateProduct;
